#!/bin/bash

#####################################################################
# Proxy Toggle Script for O2 VPN
# Toggles between VPN mode (with proxy) and direct mode (no proxy)
# NOTE: Must be run with bash, not sh!
#####################################################################

# Check if running with bash
if [ -z "$BASH_VERSION" ]; then
    echo "Error: This script must be run with bash, not sh"
    echo "Usage: bash $0 [command]  OR  ./$0 [command]"
    exit 1
fi

PROXY_URL="http://internet-proxy-b1.cz.o2:8080"
ENV_FILE="$HOME/.proxy_env"
BASHRC="$HOME/.bashrc"

# NO_PROXY list from PAC file - domains/IPs that bypass proxy
NO_PROXY_LIST="localhost,127.0.0.1,*.local,*.o2,*.telefonica,*.tesa,*.cert,*.to2cz.cz,*.to2sk.sk,*.to2sk,*.ct.cz,*.eurotel.cz,*.corp,*.cetin,10.*,17.*,172.16.*,172.17.*,172.18.*,172.19.*,172.20.*,172.21.*,172.22.*,172.23.*,172.24.*,172.25.*,172.26.*,172.27.*,172.28.*,172.29.*,172.30.*,172.31.*,192.168.*,*.o2.cz,*.o2its.cz,*.o2.sk"

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Source existing proxy config if it exists (for accurate status display)
if [ -f "$ENV_FILE" ]; then
    . "$ENV_FILE" 2>/dev/null
fi

#####################################################################
# Functions
#####################################################################

show_status() {
    printf "${BLUE}=== Proxy Status ===${NC}\n"
    if [ -f "$ENV_FILE" ] && grep -q "^export HTTP_PROXY" "$ENV_FILE" 2>/dev/null; then
        printf "Status: ${GREEN}ENABLED${NC} (VPN mode)\n"
        echo "HTTP_PROXY: $HTTP_PROXY"
        echo "HTTPS_PROXY: $HTTPS_PROXY"
        # Use cut instead of bash substring for NO_PROXY preview
        echo "NO_PROXY: $(echo "$NO_PROXY" | cut -c1-60)..."
    else
        printf "Status: ${YELLOW}DISABLED${NC} (Direct mode)\n"
        echo "No proxy configured"
    fi
    echo ""
}

enable_proxy() {
    printf "${BLUE}Enabling proxy for VPN mode...${NC}\n"

    # Create proxy environment file
    cat > "$ENV_FILE" << EOF
# O2 Corporate Proxy Configuration
# Generated by toggle-proxy.sh on $(date)

export HTTP_PROXY="$PROXY_URL"
export HTTPS_PROXY="$PROXY_URL"
export http_proxy="$PROXY_URL"
export https_proxy="$PROXY_URL"

# Bypass proxy for internal O2 domains and private networks
export NO_PROXY="$NO_PROXY_LIST"
export no_proxy="\$NO_PROXY"
EOF

    # Source the file to apply to current session
    . "$ENV_FILE"

    printf "${GREEN}✓ Proxy enabled${NC}\n"
    echo ""
    echo "Proxy URL: $PROXY_URL"
    echo "NO_PROXY configured for internal O2 domains"
    echo ""
    printf "${YELLOW}IMPORTANT: You must restart VSCode for changes to take effect!${NC}\n"
    echo "Run: killall code && code"
    echo ""
}

disable_proxy() {
    printf "${BLUE}Disabling proxy for direct mode...${NC}\n"

    # Create empty environment file or comment out proxy settings
    cat > "$ENV_FILE" << EOF
# O2 Corporate Proxy Configuration
# Generated by toggle-proxy.sh on $(date)
# PROXY DISABLED

# export HTTP_PROXY="$PROXY_URL"
# export HTTPS_PROXY="$PROXY_URL"
# export http_proxy="$PROXY_URL"
# export https_proxy="$PROXY_URL"
# export NO_PROXY="$NO_PROXY_LIST"
# export no_proxy="\$NO_PROXY"
EOF

    # Unset in current session
    unset HTTP_PROXY
    unset HTTPS_PROXY
    unset http_proxy
    unset https_proxy
    unset NO_PROXY
    unset no_proxy

    printf "${GREEN}✓ Proxy disabled${NC}\n"
    echo ""
    printf "${YELLOW}IMPORTANT: You must restart VSCode for changes to take effect!${NC}\n"
    echo "Run: killall code && code"
    echo ""
}

ensure_bashrc_sources_env_file() {
    # Check if .bashrc already sources the proxy env file
    if ! grep -q "source.*\.proxy_env" "$BASHRC" 2>/dev/null; then
        printf "${YELLOW}Adding proxy configuration to .bashrc...${NC}\n"
        cat >> "$BASHRC" << 'EOF'

# O2 Proxy Configuration (managed by toggle-proxy.sh)
if [ -f "$HOME/.proxy_env" ]; then
    source "$HOME/.proxy_env"
fi
EOF
        printf "${GREEN}✓ Added to .bashrc${NC}\n"
        echo ""
    fi
}

restart_vscode() {
    printf "${BLUE}Restarting VSCode...${NC}\n"

    # Kill all VSCode processes
    pkill -f "code" 2>/dev/null
    sleep 2

    # Start VSCode with new environment
    code &

    printf "${GREEN}✓ VSCode restarted${NC}\n"
    echo "Claude Code and Copilot should now work with the new proxy settings"
    echo ""
}

show_help() {
    echo "Proxy Toggle Script for O2 VPN"
    echo ""
    echo "Usage: bash $0 [COMMAND]  OR  ./$0 [COMMAND]"
    echo ""
    echo "Commands:"
    echo "  on              Enable proxy (for VPN mode)"
    echo "  off             Disable proxy (for direct connection)"
    echo "  status          Show current proxy status"
    echo "  restart-vscode  Restart VSCode to apply changes"
    echo "  help            Show this help message"
    echo ""
    echo "Examples:"
    echo "  bash $0 on      # Enable proxy and restart VSCode"
    echo "  bash $0 off     # Disable proxy and restart VSCode"
    echo "  bash $0 status  # Check if proxy is enabled"
    echo ""
}

#####################################################################
# Main Script
#####################################################################

# Ensure .bashrc sources our proxy env file
ensure_bashrc_sources_env_file

case "${1:-}" in
    on|enable)
        enable_proxy
        show_status
        ;;
    off|disable)
        disable_proxy
        show_status
        ;;
    status)
        show_status
        ;;
    restart-vscode|restart)
        restart_vscode
        ;;
    help|--help|-h)
        show_help
        ;;
    *)
        show_help
        exit 1
        ;;
esac

exit 0
